import React, { useState, useRef } from 'react';
import { Upload, FileAudio, Download, X, CheckCircle, AlertCircle, Loader } from 'lucide-react';

export default function AudEX() {
  const [file, setFile] = useState(null);
  const [transcription, setTranscription] = useState('');
  const [status, setStatus] = useState('idle'); // idle, processing, success, error
  const [errorMsg, setErrorMsg] = useState('');
  const [dragActive, setDragActive] = useState(false);
  const fileInputRef = useRef(null);

  const supportedFormats = [
    '.mp3', '.wav', '.m4a', '.flac', '.ogg', '.webm',
    '.mp4', '.avi', '.mov', '.mkv'
  ];

  const handleDrag = (e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setDragActive(true);
    } else if (e.type === 'dragleave') {
      setDragActive(false);
    }
  };

  const handleDrop = (e) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    
    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      handleFileSelect(e.dataTransfer.files[0]);
    }
  };

  const handleFileSelect = (selectedFile) => {
    const fileExt = '.' + selectedFile.name.split('.').pop().toLowerCase();
    if (!supportedFormats.includes(fileExt)) {
      setErrorMsg(`Unsupported file format. Please use: ${supportedFormats.join(', ')}`);
      setStatus('error');
      return;
    }
    
    setFile(selectedFile);
    setStatus('idle');
    setErrorMsg('');
    setTranscription('');
  };

  const handleFileInput = (e) => {
    if (e.target.files && e.target.files[0]) {
      handleFileSelect(e.target.files[0]);
    }
  };

  const transcribeAudio = async () => {
    if (!file) return;

    setStatus('processing');
    setErrorMsg('');

    // Simulated transcription process
    // In production, this would call your Python backend API
    try {
      await new Promise(resolve => setTimeout(resolve, 3000));
      
      // Demo transcription result
      const demoText = `This is a demonstration transcription of your audio file: "${file.name}".

In a production environment, this text would be generated by processing your audio through a speech-to-text engine like OpenAI Whisper, Google Speech-to-Text, or AssemblyAI.

The transcription would include:
- Accurate word-for-word conversion
- Proper punctuation and capitalization
- Speaker diarization (if multiple speakers)
- Timestamp markers (optional)
- Confidence scores for accuracy

Your file has been successfully processed. You can now export this transcription in your preferred format.`;

      setTranscription(demoText);
      setStatus('success');
    } catch (error) {
      setErrorMsg('Transcription failed. Please try again.');
      setStatus('error');
    }
  };

  const exportFile = (format) => {
    if (!transcription) return;

    const blob = new Blob([transcription], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `transcription_${Date.now()}.${format}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const reset = () => {
    setFile(null);
    setTranscription('');
    setStatus('idle');
    setErrorMsg('');
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      <div className="container mx-auto px-4 py-8 max-w-6xl">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex items-center justify-center gap-3 mb-4">
            <FileAudio className="w-12 h-12 text-purple-400" />
            <h1 className="text-5xl font-bold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">
              AudEX
            </h1>
          </div>
          <p className="text-gray-300 text-lg">
            Professional Audio to Text Transcription
          </p>
        </div>

        {/* Main Content */}
        <div className="grid md:grid-cols-2 gap-8">
          {/* Upload Section */}
          <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20">
            <h2 className="text-2xl font-bold text-white mb-6">Upload Audio/Video</h2>
            
            {!file ? (
              <div
                className={`border-2 border-dashed rounded-xl p-12 text-center transition-all ${
                  dragActive
                    ? 'border-purple-400 bg-purple-500/20'
                    : 'border-gray-500 hover:border-purple-400 hover:bg-white/5'
                }`}
                onDragEnter={handleDrag}
                onDragLeave={handleDrag}
                onDragOver={handleDrag}
                onDrop={handleDrop}
              >
                <Upload className="w-16 h-16 mx-auto mb-4 text-purple-400" />
                <p className="text-white text-lg mb-2">
                  Drag & drop your file here
                </p>
                <p className="text-gray-400 mb-4">or</p>
                <button
                  onClick={() => fileInputRef.current?.click()}
                  className="bg-purple-600 hover:bg-purple-700 text-white px-6 py-3 rounded-lg font-semibold transition-colors"
                >
                  Browse Files
                </button>
                <input
                  ref={fileInputRef}
                  type="file"
                  className="hidden"
                  accept={supportedFormats.join(',')}
                  onChange={handleFileInput}
                />
                <p className="text-gray-500 text-sm mt-4">
                  Supported formats: MP3, WAV, M4A, FLAC, OGG, MP4, AVI, MOV, MKV
                </p>
              </div>
            ) : (
              <div className="space-y-4">
                <div className="bg-white/5 rounded-lg p-4 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <FileAudio className="w-8 h-8 text-purple-400" />
                    <div>
                      <p className="text-white font-medium">{file.name}</p>
                      <p className="text-gray-400 text-sm">
                        {(file.size / 1024 / 1024).toFixed(2)} MB
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={reset}
                    className="text-gray-400 hover:text-white transition-colors"
                  >
                    <X className="w-6 h-6" />
                  </button>
                </div>

                <button
                  onClick={transcribeAudio}
                  disabled={status === 'processing'}
                  className="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 disabled:from-gray-600 disabled:to-gray-600 text-white px-6 py-4 rounded-lg font-semibold transition-all text-lg flex items-center justify-center gap-2"
                >
                  {status === 'processing' ? (
                    <>
                      <Loader className="w-5 h-5 animate-spin" />
                      Processing...
                    </>
                  ) : (
                    'Start Transcription'
                  )}
                </button>

                {status === 'error' && (
                  <div className="bg-red-500/20 border border-red-500/50 rounded-lg p-4 flex items-start gap-3">
                    <AlertCircle className="w-5 h-5 text-red-400 mt-0.5" />
                    <p className="text-red-200">{errorMsg}</p>
                  </div>
                )}

                {status === 'success' && (
                  <div className="bg-green-500/20 border border-green-500/50 rounded-lg p-4 flex items-start gap-3">
                    <CheckCircle className="w-5 h-5 text-green-400 mt-0.5" />
                    <p className="text-green-200">Transcription completed successfully!</p>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Results Section */}
          <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20">
            <h2 className="text-2xl font-bold text-white mb-6">Transcription Result</h2>
            
            {transcription ? (
              <div className="space-y-4">
                <div className="bg-white/5 rounded-lg p-4 max-h-96 overflow-y-auto">
                  <p className="text-gray-200 whitespace-pre-wrap leading-relaxed">
                    {transcription}
                  </p>
                </div>

                <div className="space-y-3">
                  <p className="text-white font-semibold">Export Options:</p>
                  <div className="grid grid-cols-3 gap-3">
                    <button
                      onClick={() => exportFile('txt')}
                      className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-3 rounded-lg font-semibold transition-colors flex items-center justify-center gap-2"
                    >
                      <Download className="w-4 h-4" />
                      TXT
                    </button>
                    <button
                      onClick={() => exportFile('docx')}
                      className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-3 rounded-lg font-semibold transition-colors flex items-center justify-center gap-2"
                    >
                      <Download className="w-4 h-4" />
                      DOCX
                    </button>
                    <button
                      onClick={() => exportFile('pdf')}
                      className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-3 rounded-lg font-semibold transition-colors flex items-center justify-center gap-2"
                    >
                      <Download className="w-4 h-4" />
                      PDF
                    </button>
                  </div>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center h-96 text-gray-500">
                <FileAudio className="w-20 h-20 mb-4 opacity-50" />
                <p className="text-lg">No transcription yet</p>
                <p className="text-sm">Upload and process a file to see results</p>
              </div>
            )}
          </div>
        </div>

        {/* Info Section */}
        <div className="mt-8 bg-white/5 backdrop-blur-lg rounded-2xl p-6 border border-white/10">
          <h3 className="text-white font-semibold mb-3">Features:</h3>
          <div className="grid md:grid-cols-3 gap-4 text-gray-300 text-sm">
            <div>
              <CheckCircle className="w-4 h-4 inline mr-2 text-green-400" />
              Drag & drop interface
            </div>
            <div>
              <CheckCircle className="w-4 h-4 inline mr-2 text-green-400" />
              Multiple audio/video formats
            </div>
            <div>
              <CheckCircle className="w-4 h-4 inline mr-2 text-green-400" />
              Export to TXT, DOCX, PDF
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}